project:
  type: website

website:
  title: "Jakobsweg Göppingen"
  description: Der Jakobsweg Göppingen führt durch den Landkreis Göppingen. Der Wanderweg führt durch Wälder, Berge, Dörfer und Städte. Familien, Pilger, Reisende alle sind wilkommen.
  image: images/logo.png
  locale: de_DE
  favicon: images/logo.png
  twitter-card: true
  opengraph: true
  page-navigation: true
  search: true
  navbar:
    logo: images/logo.png
    background: light
    left:
    - href: index.qmd
      text: Startseite
    - href: wegbeschreibung.qmd
      text: Wegbeschreibung
    - href: karte.qmd
      text: Karte 
    - href: bilder.qmd
      text: Bilder
    - href: ueberuns.qmd
      text: Über uns
  page-footer:
    left: |
      Jakobsweg Initative
    right:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
format:
  html:
    toc: true
    theme: yeti
    css: styles.css


