
# Mitmachen und Helfen

## Wie soll unser Landkreis in 10 Jahren aussehen?

Unser Göppinger Landkreis hat sich in den letzten Jahren rasch gewandelt. Wie stellen wir Bürger uns darauf ein? Benötigen wir neue Werte, Lebensstile oder Strukturen? Welche? Wie können wir globalen Veränderungen und eigenen Lebensübergängen gelassen und konstruktiv begegnen?

Essen und Trinken sind lebensnotwendig, Geld und ein guter und sicherer Arbeitsplatz sind uns wichtig. - Aber : Was ist, wenn es anders kommt? Wie robust sind wir bei neuen, unerwarteten Anforderungen? Wie können wir mit Neuem umgehen? Wie können wir selber in schwierigen Situationen aktiv werden und mitbestimmen, in unserem Handeln einen Sinn sehen? Wissen wir noch, dass wir Teil der Natur und von ihr abhängig sind?

Was kann man tun?

Interessieren Sie diese Fragen? Haben Sie Lust, bei der Entwicklung des Jakobswegs und GesundheitsPfads diese Fragen mit zu beantworten?

Entlang des Jakobswegs in Spanien entstehen immer wieder neue, kleine Wegstationen, mit Pilger-Symbolen, weisen Worten, Kunstwerken oder anderen Impulse. Sie regen den Wanderer an und machen nachdenklich. Sie werden fotografiert oder im Kopf als Bilder mit nach Hause genommen.

Auch am Göppinger Jakobsweg gibt es schon solche Wegstationen. Einige sind alt, andere sind neu. Weitere wollen wir zusammen planen. - Vielleicht öffnen und erweitern diese Bilder unsere Blicke und beeinflussen unsere eigene Welt positiv

Wir freuen wir uns, wenn Sie zu unserem nächsten Treffen kommen oder auf eine andere Weise zu uns stoßen. Die uns verbindende Themen sind z.B. die Wegbeschilderung, Erforschung der örtlichen Geschichte am JakobswegGP, Begleitung der Pilger-Unterkünfte, Baumpflanzungen am Wegrand, Entwicklung von Themenstationen des GesundheitsPfad zu Sport, Glauben, Natur, Tägliches-Brot und Medizin.

Wir freuen uns auf Ihr Kommen!

## Stempelheft

Nicht nur Kinder benutzen gerne den neuen **Stempelpass** und sammeln **PILGERSTEMPEL** an inzwischen über einem halben Dutzend Orten am Göppinger Jakobsweg und GesundheitsPfad ! - Das [Stempelheft](Stempelheft_2010-12.Pdf) hier ausdrucken!! Viel Spass beim Sammeln !!

## Spendenkonto

Wie wird das Projekt finanziert? Wir wollen das Meiste ehrenamtlich machen. Die Beschilderung des Wegs ist seit Juli abgeschlossen und weitgehend bezahlt. - Der Wegerhalt und die Themen-Stationen sind unsere nächsten Herausforderungen; Spenden sind willkommen!

Spendenbescheinigungen durch die gemeinnützige Initiative "JakobswegGP / GesundheitsPfad" e.V.

## Neue Ideen / Verbesserungsvorschläge

Wir freuen uns über jeden Kommentar oder Verbesserungsvorschlag. Bitte eine Email an: [ernst.schumacher\@web.de](mailto:ernst.schumacher@web.de){.email} richten.

## Gästebuch

Juni 2010: Familie Weber mit 3 Kindern im Vor- und Grundschulalter empfiehlt [Pilgern mit Kindern](PilgermitKindern.pdf)

Ich bin im Oktober den Weg von Göppingen bis Notzingen gelaufen. Ich kann sagen, es war ein wunderbarer Tag und ich habe es sehr genossen. Der Weg ist ganz hervorragend ausgeschildert. Nur an zwei Stellen habe ich kleinere Schwierigkeiten gehabt: 1. Wenn der weg hinter Jebenhausen in Richtung Schopflenberg geht, habe ich mich etwas verlaufen, als es am Bach entlang ging. 2. Wenn man aus dem Tal auf den Uhland-Hof zugehen will, wäre es geschickt, wenn an der Brücke auch ein Zeichen wäre. Ansonsten herzlichen Glückwunsch Manfred Hermenau, Göppingen

Danke für die Hinweise! - Die Strecke hinter dem Jebenhausener Schloß über die Wiese in Richtung Schopflenberg haben wir geändert. Er führt jetzt als schmaler Graspfad diesseits des Bachs durch das Wiestal bis nach Schopflenberg. Ernst Schumacher
