# Etappe: Bargau - Hohenstaufen (23km)
Der Jakobsweg Göppingen beginnt in Bargau an der **Jakobskirche**. Von dort geht es hinauf zum **Hornberg**. Vorbei an der Holzofen-Backstube in Herdtlinsweiler. Am Flugplatz vorbei führ der Weg zum **Kalten Feld**. Dort können wir im [Knörzerhaus](http://www.knoerzerhaus.com/) oder im hier abgebildeten [Franz-Keller-Haus](https://tuerme-wanderheime.albverein.net/wanderheime/wanderheim-franz-keller-haus/) des Schwäbischen Albvereins übernachten. Weiter geht´s hinunter zur **Reiterleskapelle**. Und dann an den Stauferbergen vorbei. Je nach Jahreszeiten sind hier viele Tagesausflügler, die die alten Kaiserberge bewundern wollen. Der Jakobsweg führt am **Stuifen** vorbei nach **Rechberg**. Dort finden wir die [Ruine Rechberg](http://de.wikipedia.org/wiki/Ruine_Hohenrechberg). Es gibt dort Möglichkeiten zum Rasten und Übernachten im Haus Rechberg, gelegen zwischen Himmel und Erde. Von Rechberg aus geht es über einen schönen Kammweg weiter nach **Hohenstaufen** (Übernachtungsmöglichkeit in der Jugendherberge [www.jugendherberge-hohenstaufen.de](http://www.jugendherberge-hohenstaufen.de/) 

> Highlight: In der [**Holzofen-Backstube**](https://www.hofcafe-mangold.de/backstube.html) in Herdtlinsweiler kann man eine Rast einlegen. Es gibt ein Hofcafé. In zwei großen Öfen, die ausschließlich mit Holz befeuert werden, wird jeden Tag frisches Brot gebacken. In der offnen Backstube kann man den Bäckern über die Schulter schauen.

> Highlight: Auf dem Flugplatz ist eine Flugschule mit Lehrpfad beheimatet. Im Lehrpfad tauchen Sie ein in die Geschichte des Hornbergs. Der Hornberg gehört zu den ältesten Segelfluggeländen und steht gleichzeitig für moderne Segelflugtechnik und -ausbildung. Es werden Führungen angeboten [Segelflugschule](https://www.bwlv.de/)

> Highlight: Auf dieser Etappe läuft der geplante Jakobsweg-GP teils zusammen mit den **Glaubens- und Schöpfungswegen** [www.glaubenswege.de](http://www.glaubenswege.de) oder er kreuzt diese. Es geht durch herrliche Natur, vorbei an Kirchen, Kapellen und Wegkreuzen mit ihren Geschichten und sakralen Orten, "welche die tiefen Wurzeln der Bewohner dieser Gegend mit der Heimat und dem Glauben widerspiegeln". Geist und Seele lassen sich durch Geschichten, Sagen und religiöse Orte inspirieren. Die Glaubenswege laden über verschiedene Rundwanderwege zu weiteren spirituellen Orten ein.

# Etappe: Hohenstaufen - Göppingen - Jebenhausen (21 km)
Diese Etappe beginnt an der [**Barbarossakirche St. Jakobus**](https://de.wikipedia.org/wiki/Barbarossakirche_St._Jakobus) in Hohenstaufen. 
Unsere Fußreise führt uns durch den Gemeindewald bis zum „Gasleitungs-Weg". Unterhalb der Kastanien-Allee in Höhe des Hörnles fordern uns Langholzbalken am Wegrand zu Balance- und Koordinationsübungen auf. Können Sie mit geschlossenen Augen auf einem Balken balancieren?

> Highlight: **Jakobuskirche in Hohenstaufen** Sie ist ein bedeutender Sakralbau des historischen Jakobspilgerwegs aus dem Mittelalter. Heute gehört sie der evangelischen Gemeinde und wird von der katholischen Gemeinde genutzt. Sie ist ein Beispiel dafür, dass es möglich ist, mit religiösen Unterschieden gelassen umzugehen. wichtige Vorraussetzung für den Erhalt des Friedens, dem wichtigsten Fundament von Leben und Gesundheit. - Auch die nächsten beiden Stationen gelten diesem Thema: das Grab des Nato-Generalsekretärs Manfred Wörner und das Kriegsgefallenen-Denkmal, auf dem in langer Reihe die im 1. und 2.Weltkrieg gefallenen Söhne des Ortes aufgelistet sind [Wikipedia-Artikel zu Burg_Hohenstaufen](http://de.wikipedia.org/wiki/Burg_Hohenstaufen)

Am Wegabzweig nach Eschenbäche erwartet die Pilgerin, bzw. den Pilger die Eislinger Stempelstelle am Jakobsweg. Ein Pilgertagebuch für Einträge liegt ebenfalls hier aus. In Eschenbäche ist ein kleiner Weiler in einer Waldlichtung mit einem traditionellen Kuhstall. Wir lernen dabei mehr über „Unser Tägliches Brot": Wie könnten wir Arbeitsplätze in der Landwirtschaft erhalten? Welche ortsnah hergestellte Nahrung ist gesünder als anderes Essen? Brauchen wir eigene Ernährungs-Souveränität? Können wir durch unser Kaufverhalten mitbestimmen?

> Highlight: **Kastanien-Allee auf der Alten Steige** Die Bäume der Allee wurden 1909 angepflanzt, um die damals neu verlegte Wasserleitung vor Sonnenhitze zu schützen. Alte Hohenstaufer berichten, dass sich im 2.Weltkrieg die Flackhelfer von der Bergspitze in den Schutz der Kastanienbäume des Hohlwegs flüchteten. Bäume wurzeln in der Erde und verzweigen sich zum Himmel. Erst spät haben wir Menschen den Schutz ihrer Kronen verlassen. Sie schützen vor Hitze, sie binden Wasser und sorgen für gesundes Klima. Sie verarbeiten CO2 und sichern damit unser Leben. - Könnten nicht Alleebäume am Wegrand zu einem Erkennungsmerkmal für unseren Gesundheitspfad werden? 

Südlich der Alten Steige schweift unser Blick ostwärts zum „Immenreich" (Reich der Bienen). Es ist ein verwunschenes Gartenhausgebiet mit verschiedensten Wiesenblumen, sogar Orchideen und mit einem altem Baumbestand, der anderenorts ausgestorbenen Tieren Heimstatt ist: Fledermäusen, Siebenschläfer, Halsbandschnäpper, Rotkopfwürger und Wendehals. Die Naturschutzverbände bemühen sich seit langem um die Anerkennung als Schutzgebiet. Das **Immenreich** wird auch „Tal der Liebe" im Volksmund genannt.

> Exkurs: **Der Gesundheits-Baum** Der Wald und seine Bäume spielen für die Menschen schon immer eine wichtige Rolle. Neben der seit Jahrhunderten erfolgten Nutzung des Waldes gewinnt seine Erholungs- und Gesundheitsfunktion in unserem dicht besiedelten Land immer mehr an Bedeutung. Der an dieser Station ausgewählte Gesundheitsbaum will, stellvertretend für alle anderen Bäume zeigen, was er alles für unser Wohlbefinden und unsere Gesundheit macht. So liefert er zum Beispiel Sauerstoff, spendet im Sommer Schatten und reinigt die Luft von Staub und Krankheitserregern.

Wir verlassen Eschenbäche, folgen der Krumm nach Süden und erproben bei der Bachüberquerung die **Kneipp-Therapie** . Was wissen wir über die Naturheilkunde des Pfarrer Kneipp? Kennen Sie etwa schon die fünf Gesundheits-Säulen seiner Therapie? Die Kneipp-Station finden Sie an der Stelle wo der Weg das Bächlein Krumm vor Krummwälde überquert

> Hightlight: **Kneipp-Station**. Die Lehre von Pfarrer Kneipp (1821 -- 1897) hat 5 Fundamente. Ganz wie die 5 Fingern der Gesundheitshand!
1.  Die Wassertherapie: Kaltes und warmes Wasser reizen und trainieren die Blutgefäße, Nerven u. Innere Organe
2.  Die Phytotherapie: Heilpflanzen sind der Ursprung der Pharmakologie. In zahlreiche Arzneiensind siebis heute Mittel der ersten Wahl. Heilpflanzenkenntnisse helfen die Gesundheit zu erhalten.
3.  Die Bewegungstherapie: Tägliche Bewegungsaktivitäten, möglichst im Freien, gehören zum kneippschen Programm.
4.  Die Ernährungstherapie: Die Empfehlungen von Pfarrer Kneipp sind in die heutige Ernährungswissenschaft aufgegangen.
5.  Die Ordnungstherapie: Beinhaltet Empfehlungen zu Biorhythmus und Harmonisierung von Leib und Seele.
Weitere Auskunft erhalten sie bei Veranstaltungen des Göppinger bei Wanderunge, Ausflügenund anderen Veranstaltungen. Weiteres unter: [https://www.kneipp-verein-goeppingen.com/](https://www.kneipp-verein-goeppingen.com/).

Nachdem wir einen Bauerngarten passiert haben, erreichen wir die [**Jakobuskapelle Krummwälden**](https://stmarkus-liebfrauen-eislingen.drs.de/geschichte-kirchen-und-kapellen/st-jakobus.html). Von Mesnerinnen und Gemeinderätin können wir mehr über ihre Geschichte, Zukunft und die Bedeutung dieser „Simultan-Kirche" für den Jakobsweg erfahren.

Wir verlassen **Krummwälden** auf der Fahrstraße/Fußgängerweg auf der linken Seite Richtung Eislingen. Auf halber Höhe zweigt der Weg links in die Streuobstwiesen ab. Es erwartet uns ein schöner Panoramablick über das Filstal zur Schwäbischen Alb mit dem Wasserberg den Fuchseck und der Burg Teck. In **Eislingen** führt der Weg eine Zeitlang durch die Wohnsiedlung, quert dann die Fahrstraße und führt durch Streuobstwiesen am Rand der Neubausiedlung vorbei. An einer T-Kreuzung führt der Weg nach links. Hier finden Sie rechter Hand ein großer Beruf-Imkerstand. 

> Exkurs: Imker ist ein traditioneller Beruf. Auch als Freizeitbeschäftigung ist es im Göppiger Voralbgebiet verbreitet. Ein umtriebiger Verein lädt zu spannenden Anfängerkursen ein. Hätten Sie Lust dabei zu sein? [Imkerverein Göppigen](http://www.imkerverein-goeppingen.de) 

Wie der Weg auf Eislinger Gemarkung verläuft können Sie auf [Eislingen-online](http://www.eislingen-online.de/2008/07_jakobsweg/eislingen.html) sehen. Nach den Überquerungen des Roßbach laufen wir vorbei an einem Trimm-dich-Pfad und von dort in die Stadt **Göppingen**. 

> Highlight: **Rastmöglichkeiten im Kleintierzuchtverein - Hasenheim** 73054 Eislingen, Tälesweg 37,verantwortl. Adelheid Braun, Tel. 07161/89455, 70 Sitzplätze mit Gartenterrasse. Öffnungszeiten Montag - Freitag 12 - 22 Uhr. Dienstag Ruhetag. Samstag ab 11 Uhr, Sonntag ab 10 Uhr. Wir züchten hier Hühner, Hasen und Enten. Die Züchter sind gerne bereit, ihre Tiere zu zeigen.

> Highlight: Eine weitere Einkehrmöglichkeit ist der**Musikantenstadel**, tägl. von 16 bis 24Uhr u. sonntags 10-24Uhr, Tälesweg 83, 73 054 Eislingen, Tel. 07161-8 70 87 (Gaststätte bewirtschaftet).

> Exkurs: **Unkraut oder Heil- und Würzkraut?** Seit Menschengedenken werden Kräuter nicht nur zum Würzen von Speisen genutzt, sondern auch als Heilmittel. Viele Kräuter werden als Unkraut verachtet. Aber wer sie kennt, schätzt den Wert der Pflanzen. So wirken zum Beispiel Brennnessel, Löwenzahn blutreinigend, entwässern den Körper und schwemmen Schlackestoffe aus. Breit- und Spitzwegerich sein frischer Saft bringt Linderung gegen kleine Wunden und Insektenstiche sowie gegen Husten. Auskunft über Anwendung und Herkunft der Heilpflanzen und Gewürzkräuter erhalten sie bei Veranstaltungen des Naturheilvereins Göppingen bei Kräuterwanderungen und Vorträge. Weiteres unter: www.naturheilverein-gp.de oder Telefon 07161/9612514 Pilger die auf ihrem Weg Schwierigkeiten mit den Füße haben legen Blätter vom Breitwegerich in den Strumpf diese kühlen. Wer leichtes Kopfweh hat kaut etwas Mädesüß und um den Speichelfluss beizubehalten nimmt man einen kleinen Stein oder Kirschkern in den Mund. - Pilger erleben auf ihrem Weg die wunderbare Welt der Natur [Heilkräuter-Lehrpfad.PDF Heilkräuter Lehrpfad (PDF)]()

> Exkurs **Lothar-Sturmwurf-Lehrpfad im Spitalwald** Der Orkan Lothar hat im Göppinger Stadtwald deutliche Spuren hinterlassen. Aber der Wald erholt sich -- oft hilft sich die Natur selbst. Der Naturpfad STURMWURF soll zeigen, wie sich Pflanzen und Tiere auf die neue Situation einstellen. Auf sieben Schautafeln erfahren die Besucher entlang des Pfades wissenswertes über den Zustand des Waldes nach dem Sturm und die mittelbaren und unmittelbaren Folgen.

> Exkurs **Russenfriedhof** 1805 schleppten russische Gefangene, die während der Napoleonischen Kriegszüge in Göppingen zusammengeführt wurden, das Gelbe Fieber bzw. Typhus ein. Der Göppinger Oberamtsarzt Dr. Friedrich Hartmann versuchte die Kranken zu isolieren. Er richtete Notlazarette ein, doch die Seuche breitete sich vor allem unter den Kriegsgefangenen weiter aus. Auch Dr. Hartmann erkrankte. Hunderte gestorbene russische Kriegsgefangene wurden namenlos im Oberholz bestattet. [Russenfriedhof](http://www.russenfriedhof.de)

> Exkurs: **Grabhügel der Kelten** Die Kelten besiedelten im 1. Jahrtausend v. Chr. weite Teile Europas. Die Grabhügel datieren von 400 bis 600 vor Christus. Die Kelten betrieben Ackerbau mit stählernen Pflügen, bauten Dinkel und Emmer als Getreide an und hielten sich Haustiere. Neben zahlreichen männlichen finden sich zahlreiche weibliche Gottheiten, die die hohe soziale Stellung der Frau widerspiegeln. Ihre Priester, die Druiden waren nicht nur Priester, sondern auch Ärzte, Richter und Politiker. Bäume galten wie bei den Römern als heilig.

In der Wolfsstrasse finden Sie vor der Hausnummer 8 Stolpersteine zum Gedenken der Opfer im Dritten Reich. Im Zentrum der Stadt ist die  [**Oberhofenkirche in Göppingen**](https://de.wikipedia.org/wiki/Oberhofenkirche_(Göppingen)). Durch die Neue Mitte und die Fußgängerzone von Göppingen führt der Weg weiter nach Süden. Nach der Innenstadt geht es zum **Christophsbad**, das Quellenwasser am Badhaus gibt es zum Nulltarif, hier oder im futuristischen Klinik-Cafe kann aufgetankt werden. Das **Museele** MuSeele - Museum für Geschichte der Psychiatrie [www.museele.de](http://www.museele.de/museele) ist auch ein Besuch wert. Von dort sind es etwa 5 Minuten Fußweg bis zum Bienenlehrpfad am Christophsbad.

> Highlight: **Bio-Kantine des Waldeckhofs** Das "Suppentöpfle" in der Göppinger Fußgängerzone (50m vom Rathaus entfernt, Poststrasse 42) bietet täglich Suppen, Salate und Snacks in Bioland- Qualität an. Gegründet hat den "anderen Imbiss" die Staufen Arbeits- und Beschäftigungsförderung (SAB), die auch den Bioland-Waldeckhof in Göppingen-Jebenhausen betreibt. **"Wir verfolgen damit zwei Ziele: gesunde Lebensmittel in Bio-Qualität anzubieten und Arbeitsplätze für Langzeitarbeitlose zu schaffen."** Vom Gaisburger Marsch über Lammtopf bis hin zu Tomatensuppe oder Maultaschen-Suppe warten jeden Tag zwei frisch zubereitete kleine Gerichte auf die hungrigen Gäste. Staufen Suppentöpfle - nur 50m vom Rathaus entfernt in der Göppinger City, Poststrasse 42.

> Highlight: **MuSeele -- Psychiatrie-Museum und Sauerwasserbrunnen** Der Fluss, das Heilwasser, die Hilfe für seelisch Kranke, die Zeit und die Vision Hier steht das alte Badhaus von Heinrich Schickhardt 1616-1618 gebaut. Das seit 1404 bekannte Sauerwasser hat hier seine Quelle. Das ehemalige Badhaus wird seit 1852 als psychiatrische Klinik genutzt. Viele moderne Bauten sind hinzugekommen und heute finden wir ein breites Spektrum an psychiatrischen, psychosomatischen, neurologischen und rehabilitativen Behandlungsangeboten sowie ein Heim. Im MuSeele, einem Museum für die Geschichte der Psychiatrie im Dachgeshcoss des Badhauses ist nicht nur die Geschichte des Christophsbades zu erleben, sondern darüber hinaus die vielfältige Thematik der Psychiatrie. Das MuSeele ist mittwochs von 16 bis 18 Uhr und sonntags von 14 bis 16 Uhr geöffnet. Führungen sind nach Voranmeldung auch ausserhalb der Öffnungszeiten möglich (Tel. 07161/601-6712). Der Eintritt beträgt 1 € pro Person. Führungen kosten zusätzlich 25 €.

> Highlight: **Bienenlehrpfad der Staufen-Imkerei** Erster Göppinger Bienenlehrpfad am Christophsbad, Zeit für eine ausgiebige Pause - Warum? Hier gibt es interessante Imkerei-Einsteigerinformationen auf Schautafeln, Nisthilfen für Insekten. Bei trockenem Wetter ist die Fluglochbeobachtung eines Bienenvolkes besonders interessant. Sitzgelegenheiten und Tisch zum Vespern ist vorhanden, ebenso eine Markise als Schattenspender. Von hier den Blick zum Hohenstaufen genießen, die Bienen beim Polleneintragen beobachten, endlich Zeit, um auf die Grundwerte des Lebens zurückzukommen, die Zufriedenheit erleben, dankbar sein für das Erlebte. Auf Wunsch auch ausführliche Führungen (Voranmeldung erforderlich) am 1. GP-Bienenlehrpfad. (Info-Tel. 07161-601 380 Borchard).- Verkauf der Bienenprodukte von Honig, Propolis, Wachskerzen und Honiglikör jederzeit. Wenn bei Borchard, Oedeweg 7, keiner da ist, dann bitte im 1. OG klingeln. Auf Wunsch Bewirtschaftung am Bienenlehrpfad, preiswert Gegrilltes, Getränke u.s.w., für Gruppen ideal. **Info Staufenimkerei-Borchard, Oedeweg 7, Tel 601 380, ab 16:00 oder** **staufenimkerei\@arcor.de** [www.staufenimkerei.npage.de](http://www.staufenimkerei.npage.de)"

An der Filsbrücke in Göppingen ist eine Christophorusskulptur errichtet worden. Der heilige Christophorus, der das Jesuskind über das Wasser trug, gilt als Patron der Pilger. Er ist auch Sinnbild für das Getragenwerden, das uneigennützige Helfen und der Zivilcourage. Die **Sausteige hinter dem Christophsbad** ist 200m vom Jakobsweg entfernt. Der Jakobsweg führt an der Fils entlang bis nach **Faurndau**. Der Fluß ist im Abschnitt zwischen Göppingen und Plochingen fast durchgängig besiedelt und industriell erschlossen. Dies lässt sich auf dieser Wegstrecke sehen. Hinter der Stiftskirche von Faurndau kommt man an der Kreuzung von Fußweg und Straße nach rechts zur **Galerie Stepanek** in der früheren katholischen Behelfskirche. Eine Plastik des Stahlbildhauers Stepanek interpretierte und übernahm der Leiter der Göppinger Parkinsonselbsthilfegruppe im deutschen Parkinson Verein als Symbol für diese Krankheit mit Verlangsamung und gestörte Bewegungen bis hin zur völligen Starre. Man kann sie auch allgemein als Symbol für eine Selbsthilfegruppe ansehen: eine tragfähige Gemeinschaft von Menschen, die zusammenstehen und in der gehalten wird, wer umzufallen droht. 

> Highlight: Galerie Stepanek geöffnet Sa+So 16-18 h. Information: Werner Stepanek (07161/24118) und Gottfried Lutz (07161/917700)

> Highlight: **Apothekergarten bei der Stiftsapotheke** Faurndau Apotheker Peter Vargha, der die Stiftsapotheke gegründet und bis 2009 geführt hat, ist es zu verdanken, dass der Platz vor der Apotheke nicht nur als banaler Parkplatz genützt wird, sondern ansprechend, wohlriechend und nutzbringend als Apothekergarten alten Stils. Das rechte Schaufenster der Apotheke will auch der neue Besitzer für Informationen über Gift-und Heilpflanzen (oft nur eine Frage der Dosis!) zur Verfügung stellen. Daran wird z.Z. noch gearbeitet.

> Highlight: **Vorplatz der Faurndauer Stiftskirche** Der Sauerwasserbrunnen auf dem Vorplatz der Stiftskirche wurde im 20. Jhd. wegen Verunreinigungen geschlossen. Die Faurndauer Bevölkerung reagierte mit nicht zu überhörendem Protest, und eine „Sauerwasser-Initiative" erreichte zusammen mit Bezirksbeirat und Kirche, dass ein neuer Brunnen aufgestellt wurde, aus dem demnächst wieder das beliebte Sauerwasser fließen soll. In der Stiftskirche liegt ein Heft mit Detailfotos zu diesem von Ulrich Henn 2007 gestalteten „Brunnen der Baemherzigkeit" (nach Matthäus 25) auf (3 €). Der **Brunnen der Barmherzigkeit** ruft mit seiner Weltkugel-Skulptur zu einer **Globalisierung der Ethik** auf: "Ich bin hungrig gewesen, und ihr habt mir Essen gegeben. Ich bin durstig gewesen, und ihr habt mir zu trinken gegeben. Ich bin ein Fremder gewesen, und ihr habt mich aufgenommen. Ich bin nackt gewesen, und ihr habt mich gekleidet. Ich bin krank gewesen, und ihr habt mich besucht. Ich bin im Gefängnis gewesen, und ihr seid zu mir gekommen." ;Dann werden sie ihm antworten und sagen: Herr, wann haben wir dich hungrig oder durstig gesehen oder als Fremden oder nackt oder im Gefängnis;? Dann wird er ihnen antworten und sagen: Wahrlich, ich sage euch: Was ihr nicht getan habt einem von diesen Geringsten, das habt ihr mir auch nicht getan."

Kurz nach der Stiftskirche in Faurndau führt der Weg am **Bioland-Bauernhof Ziegler** mit einem Hofladen vorbei. Von dort führt der Weg malerisch am Pfuhlbach entlang. Südlich der Kreuzung des Jakobswegs und der B10 befinden sich die **Wildnis-Biotope am Pfuhlbach**. In  **Jebenhausen** erreichen wir die das Ende dieser Etappe.

> Exkurs: Eine Idee bahnt sich ihren Weg - seit den 50er Jahren diskutierten süddeutsche Bäuerinnen und Bauern die Idee eines organisch-biologischen Landbaus. 1971 gründeten 12 Männer und Frauen den „bio-gemüse e.V.", den Vorläufer von Bioland. Zehn Jahre später hatte der Verein bereits 200 Mitglieder. Die Wirtschaftsweise der Bioland-Betriebe basiert auf einer Kreislaufwirtschaft - ohne synthetische Pestizide und chemisch-synthetische Stickstoffdünger. Die Tiere werden artgerecht gehalten und die Lebensmittel schonend verarbeitet. Dies ermöglicht eine umweltverträgliche und nachhaltige Lebensmittelerzeugung. Inzwischen arbeiten über 5000 Biobauern und 800 Lebensmittel-Hersteller wie Bäckereien, Metzgereien, Molkereien, Brauereien, Mühlen, Restaurants, Safthersteller nach den Bioland-Richtlinien. Bioland-Produkte sind in Hofläden, auf Wochenmärkten, in Naturkostgeschäften, in Supermärkten und über Lieferservice erhältlich. 

> Highlight: **Pfuhlbachtal nördlich von Jebenhausen** Obstbaum-Allee Die Idee des Jakobswegs begann mit dem Wunsch, im Schatten von Bäumen zu spazieren und dabei im Gespräch mit anderen auf gleicher Augenhöhe, neue Wege zu suchen und zu finden. Die hier gepflanzten Bäume wurden in einer Vater-Sohn-Enkel-Aktion im November 2008 gesetzt. Beteiligt waren drei Generationen aus: Sportverein und CVJM Jebenhausen, islamischer Ditib-Gemeinde, Akademie Bad Boll, Landesnaturschutzverband, Landwirtschaft und Kneippverein.

# Etappe: Jebenhausen- Bodeslhofen (23km)
Die dritte Tagesstrecke beginnt in **Jebenhausen** mit dem **Jüdischen Museum** [www.edjewnet.de](http://www.edjewnet.de) in der alten Ortskirche. Nach einem Schluck aus dem Sauerwassenbrunnen des Jebenhäuser Museums geht der Weg nach Schopflenberg. Vorbei am **Kleintierzüchter-Verein mit Gaststätte** Guldenöschle 2, 73035 Göppingen-Bezgenriet, Tel: 07161 - 42877 Geöffnet Mi., Do., Fr. ab 16 Uhr, Sa., So. und an Feiertagen ab 10Uhr. Von Schopflenberg geht es weiter durch das **Butzbachtal**. Zell verbleibt auf der linken Seite und Hattenhofen auf der rechten. Im schönen Butzbachtal lassen sich Bachufer, Weideland, Wiesen und Wald in schöner Eintracht anschauen. 

> Highlight: **Alte Bad-Herberge Jebenhausen** **Naturkundliches Museum** Zeigt an Hand der Sammlung Dr. Engel Fossilien aus 200 Mill. Jahre Erdgeschichte der Schwäbischen Alb und ihres Vorlandes geboten. Vogelsammlung, Schmetterlinge, Vor- und Frühgeschichte. In der Alten Badherberge Jebenhausen, Boller Straße 102, 73035 Göppingen, Tel.07161/4742, geöffnet von Mitte April bis Anfang November Mi. und Sa. von 13-17 Uhr; So. und Fei. von 11 -17 Uhr, Eintritt: 1.50 € (ermäßigt 1.00 €); Kinder, Schüler und Jugendliche bis 18 Jahre frei. Zu erreichen vom ZOB mit der Buslinie 20/21, Haltestelle. Alte Kirche; wenige Parkplätze beim Haus.

> Highlight: **Schopflenberg** **Gemeinschaftliches Oeko-Wohnprojekt** Im Jahr 1993 bauen 11 Familien mit 23 Kindern zusammen mit 11 Architekten ein gemeinschaftliches Öko-Wohnprojekt. Es umfasst 11 Häuser mit insgesamt 2700 qm Wohnfläche. Dazu gehören eine Gemeinschaftsfläche mit Spielplatz und Holzbackofen sowie eine solargestützte Heizung und eine Zisterne für Brauchwasser. Die Individualität der einzelnen Häuser ist harmonisch in das Gesamtbild eingebunden -- heute etwas Besonderes, in den mittelalterlichen Städten, die der Pilger auf seinem Weg noch passieren wird, eine Selbstverständlichkeit.

> Highlight: **Baumklettern am Schopflenberg:** Was halten Sie von einem Gutschein für einen Baumkletter-Tag, z.B. als Konfirmations- oder Gesellen- oder Abitursgeschenk? Herr Nescholta weist sie umsichtig und als erfahrener Kletterer ein. Es ist spannend 5 oder 10 Meter hoch im Eichenwipfel den Blick weit über´s Land und die Albtrauf schweifen zu lassen. [www.360-grad-schrittweise.de](http://www.360-grad-schrittweise.de)

> Exkurs: **Schopflenberg** **Gartenbau- und Kleintierzüchter-Anlage mit Gaststätte** Der Göppinger Bezirksverband der Gartenfreunde hat 19 Vereine. in denen 2300 Mitglieder organisiert sind. **Kleingärten bieten Lebensqualität durch Lebensraumvernetzung, Durchgrünung, Biotop- und Artenschutz** sinnvolle Freizeitbeschäftigung, gärtnerische Betätigung und preiswertes gesundes Gemüse **persönliche Erlebnis vom Säen, Wachsen, Gedeihen und Ernten, zwischenmenschlichen Beziehungen** Spiel- und Kommunikationsfeld, Erlebnisräume in der Natur, Anschauungsunterricht in Biologie **Entspannung vom Arbeitsstress durch gesunde Betätigung; eine ideale Alternative zum Arbeitsalltag** Arbeitslosen bieten die Kleingärten das Gefühl, gebraucht zu werden und noch dazu zugehören **Immigranten in interkulturellen Gärten die Möglichkeit Kontakte zu knüpfen und sich zu integrieren.** Behinderten bieten die Kleingärten einen Ort an dem er Kontakte knüpft und so der Isolierung entgeht \* Senioren einen Ort des Gesprächs und der Ruhe, individuelle Selbstverwirklichung im 3. Lebensabschnitt Office International du Coin de Terre et des Jardins Familiaux, Vereinigung von drei Millionen Kleingärtnern [Kleingarten-Eintrag bei Wikipedia](http://de.wikipedia.org/wiki/Kleingarten) 

> Exkurs: Steine wegwerfen hat seine Zeit und Steine sammeln hat seine Zeit (Prediger 3). Kirchenaustritte gelten vielen als selbstverständlich. Wer Paten sucht für ein Taufkind, erlebt oft im beruflichen und privaten Umfeld, dass viele Mitmenschen eben nicht mehr in der Kirche sind. **Was wegwerfen, was behalten, was wieder aufnehmen?** Kommentar einer Ungenannten: Der Glaube und das Geschenk, glauben zu können, sind für mich zunächst mal eine persönliche Sache und erst in zweiter Linie eine gemeinschaftliche. Trotzdem ist es mir wichtig einer Gemeinde und einer Kirche anzugehören. Die Kirche als Organisation und als von Menschen aufgebaute Struktur weist aus meiner Sicht viele Fehler auf. Trotzdem leistet sie einen wichtigen Beitrag in dieser Gesellschaft und hilft Menschen innerhalb und außerhalb der Kirche in Lebens- und in Glaubensfragen. Deshalb bin wieder in die Kirche eingetreten und habe mich der benachbarten Kirchengemeinde angeschlossen. Ich freue mich daran, dass wir in unserem Dorf noch eine starke Kirche haben, einen 2000 Jahre alten, gemeinnützigen Zusammenarbeit von Menschen mit in Leid und Freud gemachten Erfahrungen, die uns zu Gelassenheit und Dialog befähigt. Es wäre schade dies ohne Not aufzugeben. **Was ist Ihre Meinung zu dieser Frage?**

> Exkurs: **Welchen Strom wollen wir oder welcher Strom fließt woher wohin?** Strommast auf letztem Acker vor Wald bei Hattenhofen Strom sorgt für Licht, treibt Maschinen und Geräte. Zu Hause kommt er selbstverständlich aus der Steckdose, Tag für Tag, aber woher und zu welchem Preis für Mensch und Natur und mit welchen Folgen für kommende Generationen? Ist die Kilowattstunde zentral in einem Kohle- oder Atomkraftwerk erzeugt, wobei die Abwärme zumeist ungenutzt in Luft und Flüsse abgegeben wird -- oft auch zum Schaden der Fische. Die Risiken eines Supergaus, von Niedrigstrahlung, ungelöster Endlagerung einerseits und des sich beschleunigenden Klimawandels durch freigesetztes Kohlendioxid andererseits sind bekannt, wenn auch verdrängt. Jede Kilowattstunde aus einem Kohlekraftwerk trägt mit 0,65 kg zur globalen Temperaturerhöhung -- in Baden- Württemberg schon um 1,5 Grad -- zum Abschmelzen der Gletscher in den Alpen und im Himalaya, zum Anstieg des Meeresspiegels, zu Dürren und Überschwemmungen bei -- mit derzeit noch kaum vorstellbaren sozialen Folgen. Ein Haushalt mit 3 Personen hat in Deutschland einen durchschnittlichen Stromverbrauch von 3500 Kilowattstunden Strom mit 2,3 Tonnen CO2. Insgesamt ist ein Bundesbürger über seine motorisierte Mobilität, mit seinem Konsum, dem Wohnen, seiner Ernährung für 10,5 Tonnen der klimaschädlichen Treibhausgase verantwortlich. Global verträglich zum Erhalt des Planeten wären nur 2 Tonnen, Dies bedeutet: Energie effizienter einsetzen, Energiesparen und auf erneuerbare Energiequellen, wie Sonne, Wind, Wasser und Biomasse umsteigen. Sparen ist nötiger denn je -- und fällt schwer, besonders wenn Energie zu billig vorhanden ist. - Jobst Kraus, April 2009

Nach der Überquerung des Butzbaches gelangen wir zum Uhlandhof [www.uhlandhof.de](http://www.uhlandhof.de). An diesem geht es vorbei, durch den Schlierbacher Wald in Richtung Kirchheim. Ohmden mit seinen Urweltfunden und den Schieferbrüchen sind nicht weit vom Weg entfernt. An der im Jahr 2021 neu gebauten Straße zwischen Schlierbach und Ohmden gibt es den Grillplatz der Kreuzeiche - eine gute Möglichkeit für eine Rast. An der kleinen Wasserscheide zwischen dem Kreuzbach bzw. Schlierbach und der Lauter geht es hinauf und hinunter. Der Waldsportpfad des Stadt Kirchheim liegt nicht weit entfernt auf der linken Seite. Die weniger sportlichen können direkt nach Notzingen abbiegen und dort die **Jakobuskirche in Notzingen** anschauen. Am Bodenbach geht es weiter bis nach Bodelshofen. Wer von dort keinen Abstecher zur [Esubiuskirche](http://www.eusebiuskirche.de/seite128.htm) in Wendlingen und dem Neckar macht ist an der **Jakobuskirche in Bodelshofen** am Endpunkt des Jakobsweges Göppingen angekommen.  

> Highlight: Hier am Jakobsweg einem europaweiten Netzwerk von spirituellen Pfaden für eine bessere Zukunft und gesellschaftlichen Zusammenhalt sollen beispielhaft einige Waldbaumarten stehen, die vermutlich für den Klimawandel gut gerüstet sind. Das bedeutet natürlich bei den langen Wachstumszeiten von Bäumen dass diese Bäume nur über Jahr- zehnte, - hunderte nach und nach an Bedeutung gewinnen werden, in der Hoffnung dass die natürlich vorkommenden Baumarten noch lange durchhalten.
1. Libanonzeder (cedrus libani): Natürliche Verbreitung in der Türkei, Libanon und in Syrien, inzwischen aber auch in Italien, Iran, Bulgarien, Frankreich, Usbekistan und Israel unterwegs. Sie ist eher langsamwüchsig und liefert Holz für Tischler, Möbel und Baumaßnahmen.
2. Edelkastanie, Esskastanie (castanea sativa): Ursprünglich vermutlich aus dem südlichen Europa und Südwesten Asien stammend, ist sie seit Jahrhunderten in vielen europäischen Ländern verbreitet. Sie ist eine rasch-wüchsige Pionierbaumart und produziert wertvolles Möbel und Fassholz. Gute Bienenweide und Maronen für die Waldtiere.
3. Tulpenbaum (amerikanischer) ´(liriodendron tulipifera) Der Tulpenbaum ist eine Alternative auf Eschenstandorten, da diese durch einen Pilz stark dezimiert wird. Ursprünglich stammt er aus dem östlichen Teil von Nordamerika, wurde aber schon in Japan und Europa verbreitet. Er kann bis zu 300 Jahre alt werden.
4. Zerreiche (quercus cerris): Sie kann im Gegensatz zu Ihren Eichenschwestern starke Trockenheit aushalten. Sie hat eine große genetische Variabiliät allerdings keine sehr große Wuchsfreude und die stofflichen Holzverwendungen sind auch eingeschränkt. Die natürliche Verbreitung erstreckt sich auf Südeuropa und Kleinasien.
5. Elsbeere ( sorbus torminalis): Sie stammt aus Süd- und Mitteleuropa sowie Nordafrika und Kleinasien. Am Kaiserstuhl gibt es schon viele Jahrzehnte Versuchsflächen, die Elsbeere kann bis zu 300 Jahre alt werden. Das Holz ist wertvoll und wird sowohl im Instrumentenbau wie auch bei Tischlern und als Furnier eingesetzt.
6. Baumhasel (corylus colurna): Dieser Baum stammt aus Südeuropa, Kleinasien, von der Balkanhalbinsel, dem Norden der Türkei bis nach Afghanistan, einschließlich dem Kaukasus und Westhimalaja. Es gibt bereits Versuchsflächen in Bayern und Baden-Württemberg. Das wertvolle Holz ist vor allem in Möbeltischlereien verwertbar.
7. Wildapfel (malus sylvestris): Wildapfel und Wildbirne waren früher in den Wäldern mehr verbreitet. Die Früchte (sauer) wurden vom ärmeren Teil der Bevölkerung eingesammelt und gegessen. Das meist drehwüchsige Holz fand wegen seiner Härte Verwendung bei Drechslern und Tischlern. Diese kreierten daraus unter anderem Zahnräder für Uhren, Göpelwerke (Tretmühlen) sowie Schrauben. Schöne Stämmchen wurden gedämpft und zu Furnieren geschnitten, um damit Möbel zu verzieren. Weil das Gehölz abgesehen davon jedoch kaum Nutzwert hatte, wurde es in Feld und Wald oft abgeschnitten oder gar ausgehackt. Inzwischen hat ein Umdenken stattgefunden, nachdem man die ökologische Bedeutung des Wildapfels erkannte. Allerdings konnte bis heute nicht mit Sicherheit belegt werden, dass unser Kulturapfel vom europäischen Wildapfel abstammt.

> Highlight: **Waldlehrpfad und Versuchsfläche zur natürlichen Wiederbewaldung im „Lothar"-Bannwald** westlich der Kreuzeiche bei Schlierbach Am 26. Dezember 1999 fegte der Orkan Lothar mit Spitzengeschwindigkeiten von mehr als 200 km/h über unsere Region. Dabei gingen Millionen Bäume zu Bruch oder wurden entwurzelt. In der Folge des Sturmes befreite man die betroffenen Flächen vom Bruchholz und forstete viele dieser Wälder wieder auf. Was aber würde die Natur von sich aus mit den geschädigten Wäldern tun? Um dies zu verfolgen und vor allem um daraus Folgerungen für die Zukunft zu ziehen, wurden in verschiedenen Regionen des Landes sogenannte Bannwälder eingerichtet. In einem solchen Bannwald wird nicht vom Menschen eingegriffen, so auch hier. Auf einer Fläche von ca. 11 ha blieb alles geworfene und gebrochene Holz unaufgearbeitet liegen und die Wiederbewaldung erfolgte in Form der Sukzession (natürliche Wiederbewaldung ohne Eingriff des Menschen). Wie man sieht, hat das Verfahren sehr gut funktioniert, soll aber nur der Forschung dienen, da auch die Nutzung des Holzes aus ökologischer Sicht sehr wichtig ist. (Holz ist der Rohstoff mit der besten Ökobilanz)



